export interface DogBreed {
  value: string;
  label: string;
}

const dogBreeds: DogBreed[] = [
  { value: "affenpinscher", label: "Affenpinscher" },
  { value: "afghan_hound", label: "Afghan Hound" },
  { value: "airedale_terrier", label: "Airedale Terrier" },
  { value: "akita", label: "Akita" },
  { value: "alaskan_malamute", label: "Alaskan Malamute" },
  { value: "american_bulldog", label: "American Bulldog" },
  { value: "american_foxhound", label: "American Foxhound" },
  {
    value: "american_staffordshire_terrier",
    label: "American Staffordshire Terrier",
  },
  { value: "american_water_spaniel", label: "American Water Spaniel" },
  { value: "anatolian_shepherd_dog", label: "Anatolian Shepherd Dog" },
  { value: "australian_cattle_dog", label: "Australian Cattle Dog" },
  { value: "australian_shepherd", label: "Australian Shepherd" },
  { value: "australian_terrier", label: "Australian Terrier" },
  { value: "basenji", label: "Basenji" },
  { value: "basset_hound", label: "Basset Hound" },
  { value: "beagle", label: "Beagle" },
  { value: "bearded_collie", label: "Bearded Collie" },
  { value: "beauceron", label: "Beauceron" },
  { value: "bedlington_terrier", label: "Bedlington Terrier" },
  { value: "belgian_malinois", label: "Belgian Malinois" },
  { value: "belgian_sheepdog", label: "Belgian Sheepdog" },
  { value: "belgian_tervuren", label: "Belgian Tervuren" },
  { value: "bernese_mountain_dog", label: "Bernese Mountain Dog" },
  { value: "bichon_frise", label: "Bichon Frise" },
  { value: "black_and_tan_coonhound", label: "Black and Tan Coonhound" },
  { value: "black_russian_terrier", label: "Black Russian Terrier" },
  { value: "bloodhound", label: "Bloodhound" },
  { value: "border_collie", label: "Border Collie" },
  { value: "border_terrier", label: "Border Terrier" },
  { value: "borzoi", label: "Borzoi" },
  { value: "boston_terrier", label: "Boston Terrier" },
  { value: "bouvier_des_flandres", label: "Bouvier des Flandres" },
  { value: "boxer", label: "Boxer" },
  { value: "briard", label: "Briard" },
  { value: "brittany", label: "Brittany" },
  { value: "brussels_griffon", label: "Brussels Griffon" },
  { value: "bull_terrier", label: "Bull Terrier" },
  { value: "bulldog", label: "Bulldog" },
  { value: "bullmastiff", label: "Bullmastiff" },
  { value: "cairn_terrier", label: "Cairn Terrier" },
  { value: "canaan_dog", label: "Canaan Dog" },
  { value: "cane_corso", label: "Cane Corso" },
  { value: "cardigan_welsh_corgi", label: "Cardigan Welsh Corgi" },
  {
    value: "cavalier_king_charles_spaniel",
    label: "Cavalier King Charles Spaniel",
  },
  { value: "chesapeake_bay_retriever", label: "Chesapeake Bay Retriever" },
  { value: "chihuahua", label: "Chihuahua" },
  { value: "chinese_crested", label: "Chinese Crested" },
  { value: "chinese_shar_pei", label: "Chinese Shar-Pei" },
  { value: "chow_chow", label: "Chow Chow" },
  { value: "clumber_spaniel", label: "Clumber Spaniel" },
  { value: "cocker_spaniel", label: "Cocker Spaniel" },
  { value: "collie", label: "Collie" },
  { value: "curly-coated_retriever", label: "Curly-Coated Retriever" },
  { value: "dachshund", label: "Dachshund" },
  { value: "dalmatian", label: "Dalmatian" },
  { value: "dandie_dinmont_terrier", label: "Dandie Dinmont Terrier" },
  { value: "doberman_pinscher", label: "Doberman Pinscher" },
  { value: "dogo_argentino", label: "Dogo Argentino" },
  { value: "english_cocker_spaniel", label: "English Cocker Spaniel" },
  { value: "english_setter", label: "English Setter" },
  { value: "english_springer_spaniel", label: "English Springer Spaniel" },
  { value: "english_toy_spaniel", label: "English Toy Spaniel" },
  { value: "entlebucher_mountain_dog", label: "Entlebucher Mountain Dog" },
  { value: "field_spaniel", label: "Field Spaniel" },
  { value: "finnish_spitz", label: "Finnish Spitz" },
  { value: "flat-coated_retriever", label: "Flat-Coated Retriever" },
  { value: "french_bulldog", label: "French Bulldog" },
  { value: "german_pinscher", label: "German Pinscher" },
  { value: "german_shepherd_dog", label: "German Shepherd Dog" },
  { value: "german_shorthaired_pointer", label: "German Shorthaired Pointer" },
  { value: "german_wirehaired_pointer", label: "German Wirehaired Pointer" },
  { value: "giant_schnauzer", label: "Giant Schnauzer" },
  { value: "glen_of_imaal_terrier", label: "Glen of Imaal Terrier" },
  { value: "golden_retriever", label: "Golden Retriever" },
  { value: "gordon_setter", label: "Gordon Setter" },
  { value: "great_dane", label: "Great Dane" },
  { value: "great_pyrenees", label: "Great Pyrenees" },
  { value: "greater_swiss_mountain_dog", label: "Greater Swiss Mountain Dog" },
  { value: "greyhound", label: "Greyhound" },
  { value: "harrier", label: "Harrier" },
  { value: "havanese", label: "Havanese" },
  { value: "ibizan_hound", label: "Ibizan Hound" },
  { value: "icelandic_sheepdog", label: "Icelandic Sheepdog" },
  { value: "irish_red_and_white_setter", label: "Irish Red and White Setter" },
  { value: "irish_setter", label: "Irish Setter" },
  { value: "irish_terrier", label: "Irish Terrier" },
  { value: "irish_water_spaniel", label: "Irish Water Spaniel" },
  { value: "irish_wolfhound", label: "Irish Wolfhound" },
  { value: "italian_greyhound", label: "Italian Greyhound" },
  { value: "japanese_chin", label: "Japanese Chin" },
  { value: "keeshond", label: "Keeshond" },
  { value: "kerry_blue_terrier", label: "Kerry Blue Terrier" },
  { value: "komondor", label: "Komondor" },
  { value: "kuvasz", label: "Kuvasz" },
  { value: "labrador_retriever", label: "Labrador Retriever" },
  { value: "lagotto_romagnolo", label: "Lagotto Romagnolo" },
  { value: "lakeland_terrier", label: "Lakeland Terrier" },
  { value: "leonberger", label: "Leonberger" },
  { value: "lhasa_apso", label: "Lhasa Apso" },
  { value: "lowchen", label: "Lowchen" },
  { value: "maltese", label: "Maltese" },
  { value: "manchester_terrier", label: "Manchester Terrier" },
  { value: "mastiff", label: "Mastiff" },
  { value: "miniature_bull_terrier", label: "Miniature Bull Terrier" },
  { value: "miniature_pinscher", label: "Miniature Pinscher" },
  { value: "miniature_schnauzer", label: "Miniature Schnauzer" },
  { value: "neapolitan_mastiff", label: "Neapolitan Mastiff" },
  { value: "newfoundland", label: "Newfoundland" },
  { value: "norfolk_terrier", label: "Norfolk Terrier" },
  { value: "norwegian_buhund", label: "Norwegian Buhund" },
  { value: "norwegian_elkhound", label: "Norwegian Elkhound" },
  { value: "norwegian_lundehund", label: "Norwegian Lundehund" },
  { value: "norwich_terrier", label: "Norwich Terrier" },
  {
    value: "nova_scotia_duck_tolling_retriever",
    label: "Nova Scotia Duck Tolling Retriever",
  },
  { value: "old_english_sheepdog", label: "Old English Sheepdog" },
  { value: "otterhound", label: "Otterhound" },
  { value: "papillon", label: "Papillon" },
  { value: "parson_russell_terrier", label: "Parson Russell Terrier" },
  { value: "pekingese", label: "Pekingese" },
  { value: "pembroke_welsh_corgi", label: "Pembroke Welsh Corgi" },
  { value: "perro_de_presa_canario", label: "Perro de Presa Canario" },
  {
    value: "petit_basset_griffon_vendeen",
    label: "Petit Basset Griffon Vendeen",
  },
  { value: "pharaoh_hound", label: "Pharaoh Hound" },
  { value: "plott", label: "Plott" },
  { value: "pointer", label: "Pointer" },
  { value: "polish_lowland_sheepdog", label: "Polish Lowland Sheepdog" },
  { value: "pomeranian", label: "Pomeranian" },
  { value: "poodle", label: "Poodle" },
  { value: "portuguese_water_dog", label: "Portuguese Water Dog" },
  { value: "saint_bernard", label: "Saint Bernard" },
  { value: "silky_terrier", label: "Silky Terrier" },
  { value: "sussex_spaniel", label: "Sussex Spaniel" },
  { value: "tibetan_mastiff", label: "Tibetan Mastiff" },
  { value: "vizsla", label: "Vizsla" },
  { value: "weimaraner", label: "Weimaraner" },
  { value: "welsh_springer_spaniel", label: "Welsh Springer Spaniel" },
  {
    value: "west_highland_white_terrier",
    label: "West Highland White Terrier",
  },
  { value: "whippet", label: "Whippet" },
  {
    value: "wirehaired_pointing_griffon",
    label: "Wirehaired Pointing Griffon",
  },
  { value: "yorkshire_terrier", label: "Yorkshire Terrier" },
];

export default dogBreeds;
