import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToasterProvider from "./provider/ToastProvider";
import ImageSearchModal from "./components/Modals/ImageSearchModal";
import ImageUploadModal from "./components/Modals/ImageUploadModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Searchable",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToasterProvider />
        <ImageSearchModal />
        <ImageUploadModal />
        {children}
      </body>
    </html>
  );
}
